import { Prisma } from '../../generated/prisma/client';

export const ActivityEvent = {
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_RESTORED: 'PROJECT_RESTORED',
  PROJECT_DUPLICATED: 'PROJECT_DUPLICATED',
  PROJECT_MEMBER_ADDED: 'PROJECT_MEMBER_ADDED',
  PROJECT_MEMBER_ROLE_CHANGED: 'PROJECT_MEMBER_ROLE_CHANGED',
  PROJECT_MEMBER_REMOVED: 'PROJECT_MEMBER_REMOVED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_RENAMED: 'TASK_RENAMED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_MOVED: 'TASK_MOVED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_ASSIGNEE_CHANGED: 'TASK_ASSIGNEE_CHANGED',
  TASK_PRIORITY_CHANGED: 'TASK_PRIORITY_CHANGED',
  TASK_DELETED: 'TASK_DELETED',
  COMMENT_CREATED: 'COMMENT_CREATED',
  COMMENT_UPDATED: 'COMMENT_UPDATED',
  COMMENT_DELETED: 'COMMENT_DELETED',
  GITHUB_REPOSITORY_CONNECTED: 'GITHUB_REPOSITORY_CONNECTED',
  GITHUB_REPOSITORY_DISCONNECTED: 'GITHUB_REPOSITORY_DISCONNECTED',
  GITHUB_ISSUE_LINKED: 'GITHUB_ISSUE_LINKED',
  GITHUB_ISSUE_UNLINKED: 'GITHUB_ISSUE_UNLINKED',
  TASK_CREATED_FROM_GITHUB_ISSUE: 'TASK_CREATED_FROM_GITHUB_ISSUE',
  ATTACHMENT_UPLOADED: 'ATTACHMENT_UPLOADED',
  ATTACHMENT_DELETED: 'ATTACHMENT_DELETED',
  WIKI_PAGE_CREATED: 'WIKI_PAGE_CREATED',
  WIKI_PAGE_UPDATED: 'WIKI_PAGE_UPDATED',
  WIKI_PAGE_DELETED: 'WIKI_PAGE_DELETED',
} as const;

export type ActivityEventType =
  (typeof ActivityEvent)[keyof typeof ActivityEvent];

export interface RecordActivityInput {
  type: ActivityEventType;
  description: string;
  projectId: string;
  userId: string;
  taskId?: string | null;
  metadata?: Prisma.InputJsonValue;
}
